dbsalesaovivo:
  outputs:
    dev:
      dbname: dbsalesaovivo_dnkd
      host: dpg-crs5a3l6l47c73csd1v0-a.oregon-postgres.render.com
      pass: Othc4q2ecTb0nBSv1O6zGejzRLPqJxmP
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres123
  target: dev
dbsalesaovivo_dnkd:
  outputs:
    dev:
      dbname: dbsalesaovivo_dnkd
      host: dpg-crs5a3l6l47c73csd1v0-a.oregon-postgres.render.com
      pass: Othc4q2ecTb0nBSv1O6zGejzRLPqJxmPOthc4q2ecTb0nBSv1O6zGejzRLPqJxmPOthc4q2ecTb0nBSv1O6zGeOthc4q2ecTb0nBSv1O6zGejzRLPqJxmP
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres123
  target: dev
invista:
  outputs:
    dev:
      dbname: DB_NAME_PROD=dbsalesaovivo_dnkd
      host: dpg-crs5a3l6l47c73csd1v0-a.oregon-postgres.render.com
      pass: Othc4q2ecTb0nBSv1O6zGejzRLPqJxmP
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres123
  target: dev
