version: 2

sources:
  - name: dbsalesaovivo_dnkd
    schema: public
    tables:
      - name: commodities
        description: "Tabela que contém dados históricos de commodities"
        columns:
          - name: Date
            description: "Data de observação"
          - name: Close
            description: "Preço de fechamento da commoditie"
          - name: simbolo
            description: "Símbolo da commoditie"

      - name: movimentacao_commodities
        description: "Tabela seed"
        columns:
          - name: date
            description: "Data da transação"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Tipo de transação (buy/sell)"
          - name: quantity
            description: "Quantidade transacionada"
